(ns ring.util.http-predicates-test
  (:require [clojure.test :refer :all]
            [ring.util.http-predicates :refer :all]))


(deftest http-status-code-predicates-test

  (testing "Informational"
    (is (continue? {:status 100}))
    (is (switching-protocols? {:status 101}))
    (is (processing? {:status 102}))
    (is (informational? {:status 101})))

  (testing "Success"
    (is (ok? {:status 200}))
    (is (created? {:status 201}))
    (is (accepted? {:status 202}))
    (is (non-authoritative-information? {:status 203}))
    (is (no-content? {:status 204}))
    (is (reset-content? {:status 205}))
    (is (partial-content? {:status 206}))
    (is (multi-status? {:status 207}))
    (is (already-reported? {:status 208}))
    (is (im-used? {:status 226}))
    (is (success? {:status 205})))

  (testing "Redirection"
    (is (multiple-choices? {:status 300}))
    (is (moved-permanently? {:status 301}))
    (is (found? {:status 302}))
    (is (see-other? {:status 303}))
    (is (not-modified? {:status 304}))
    (is (use-proxy? {:status 305}))
    (is (temporary-redirect? {:status 307}))
    (is (permanent-redirect? {:status 308}))
    (is (redirection? {:status 305})))

  (testing "ClientError"
    (is (bad-request? {:status 400}))
    (is (unauthorized? {:status 401}))
    (is (payment-required? {:status 402}))
    (is (forbidden? {:status 403}))
    (is (not-found? {:status 404}))
    (is (method-not-allowed? {:status 405}))
    (is (not-acceptable? {:status 406}))
    (is (proxy-authentication-required? {:status 407}))
    (is (request-timeout? {:status 408}))
    (is (conflict? {:status 409}))
    (is (gone? {:status 410}))
    (is (length-required? {:status 411}))
    (is (precondition-failed? {:status 412}))
    (is (request-entity-too-large? {:status 413}))
    (is (request-uri-too-long? {:status 414}))
    (is (unsupported-media-type? {:status 415}))
    (is (requested-range-not-satisfiable? {:status 416}))
    (is (expectation-failed? {:status 417}))
    (is (enhance-your-calm? {:status 420}))
    (is (unprocessable-entity? {:status 422}))
    (is (locked? {:status 423}))
    (is (failed-dependency? {:status 424}))
    (is (unordered-collection? {:status 425}))
    (is (upgrade-required? {:status 426}))
    (is (precondition-required? {:status 428}))
    (is (too-many-requests? {:status 429}))
    (is (request-header-fields-too-large? {:status 431}))
    (is (retry-with? {:status 449}))
    (is (blocked-by-windows-parental-controls? {:status 450}))
    (is (unavailable-for-legal-reasons? {:status 451}))
    (is (client-error? {:status 431})))

  (testing "ServerError"
    (is (internal-server-error? {:status 500}))
    (is (not-implemented? {:status 501}))
    (is (bad-gateway? {:status 502}))
    (is (service-unavailable? {:status 503}))
    (is (gateway-timeout? {:status 504}))
    (is (http-version-not-supported? {:status 505}))
    (is (variant-also-negotiates? {:status 506}))
    (is (insufficient-storage? {:status 507}))
    (is (loop-detected? {:status 508}))
    (is (bandwidth-limit-exceeded? {:status 509}))
    (is (not-extended? {:status 510}))
    (is (network-authentication-required? {:status 511}))
    (is (network-read-timeout? {:status 598}))
    (is (network-connect-timeout? {:status 599}))
    (is (server-error? {:status 504}))))
